### ISSUE TITLE
Unable to programmatically configure as prettifier 

### ISSUE THREAD

**Issue by dnjstrom** [pinojs/pino-http-print#12]
When trying to configure the prettier programmatically I get the following error:

```
/Users/xxx/Code/pino-test/node_modules/readable-stream/lib/_stream_readable.js:631
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/Users/xxx/Code/pino-test/node_modules/readable-stream/lib/_stream_readable.js:631:8)
    at /Users/xxx/Code/pino-test/node_modules/pino-http-print/index.js:83:29
    at Object.write (/Users/xxx/Code/pino-test/node_modules/pino/lib/tools.js:281:25)
    at Pino.write (/Users/xxx/Code/pino-test/node_modules/pino/lib/proto.js:176:15)
    at Pino.LOG [as info] (/Users/xxx/Code/pino-test/node_modules/pino/lib/tools.js:57:21)
    at Object.<anonymous> (/Users/xxx/Code/pino-test/index.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```

Minimal reproduction:
```js
const pino = require("pino");
const pinoHttpPrint = require("pino-http-print");

const logger = pino({
  prettyPrint: {},
  prettifier: pinoHttpPrint,
});

logger.info("Some log message");
```

As I've understood it, the preferred way to use pino-http-print is via the command-line interface, but in my case I'd like to pass in arguments to both it and pino-pretty (i.e. `... | pino-http-print --all --lax --ignore req` which isn't allowed by the cli). The programmatic config seems like it should handle the args correctly, but fails with the error above.

Have I misunderstood how to set things up somehow or is this a bug? Should I perhaps prefer a different approach?

**Comment by mcollina** [comment]
you should pass it as a `stream` not as `prettifier`.

**Comment by dnjstrom** [comment]
Alright, with your hint along with more tinkering and documentation reading I figured out how to get the setup above. Like you said, the key misunderstanding is that `pino-http-print` isn't a prettifier but a stream destination. So a joint setup with `express`, `pino-http`, `pino-http-print` and `pino-debug` now looks something like this for me:

```js
"use strict";

// Configure logging
const printerFactory = require("pino-http-print");
const printer = printerFactory({
  all: true,
  lax: true,
  relativeUrl: true,
  translateTime: "HH:MM:ss.l",
}, {
  ignore: "req,pid,hostname",
});

const pino = require("pino");
const logger = pino({
  level: process.env.LOG_LEVEL || "info",
}, printer());

const pinoDebug = require("pino-debug");
pinoDebug(logger, { map: { "*": "trace" } });

var middleware = require("pino-http")(
  {
    logger,
  },
);

// Start server
const app = require("express")();

app.use(middleware);

logger.info("Logging outside express context.");

app.get("/", function (req, res) {
  req.log.info("Logging inside express context.");
  res.send("hello world");
});

app.listen(3000);
```

And produces dev logs similar to this:

```
[10:47:50.981] INFO     : Logging outside express context.
[10:47:51.046] TRACE    : set "x-powered-by" to true
    ns: "express:application"

... lots more trace logs ...

[10:47:53.955] TRACE    : dispatching GET /
    ns: "express:router"
[10:47:53.955] TRACE    : query  : /
    ns: "express:router"
[10:47:53.955] TRACE    : expressInit  : /
    ns: "express:router"
[10:47:53.955] TRACE    : loggingMiddleware  : /
    ns: "express:router"
[10:47:53.956] INFO     : Logging inside express context.
[10:47:53.956] GET / 200 0ms

```

This get's me pretty close to my desired output in development (the `ns` could be formatted nicer, but it's a pretty rare use case anyhow so not crucial). Thanks for the help!

**Comment by aaestrada** [comment]
Hello @dnjstrom and @mcollina ... Is this config recommended for prod env?

could you shared me more docs regarding how we need to manage logs for production environment... Please!!
